### ISSUE TITLE
New name, new icon

### ISSUE THREAD

**Issue by Zabriskije** [MuhammedKpln/spamify#12]
Hi Muhammed, I saw you changed the app name, so here's your new app icon:

<img width="256" src="https://user-images.githubusercontent.com/101254295/221984280-836347d0-a864-4e4f-961c-8e4b7ca44a6d.png">

Are you sure about that name, though? 👀
Spamify was nice.

**Comment by MuhammedKpln** [comment]
Well Spamify sounded more like a application for creating/sending the spam, so that's why i wanted to change. Suggestions are always welcome! :) Thanks for editing the icon! Really appreciated.

**Comment by Zabriskije** [comment]
@MuhammedKpln I've given it some thought:
- Dumm-e-mail
- Shamail

**Comment by MuhammedKpln** [comment]
Thank you for your suggestions but i think the name of "BarBox" serves the purpose.
