### ISSUE TITLE
Menu bar icon looks ugly 

### ISSUE THREAD

**Issue by neorrk** [MuhammedKpln/spamify#4]
![image](https://user-images.githubusercontent.com/58256328/160292902-3ed49142-7ddd-471a-b423-a3c69c4c927a.png)
![image](https://user-images.githubusercontent.com/58256328/160293193-15362adc-9b60-4618-a0e9-1ed2f201d27d.png)

It looks out of place on a bright background.

**Comment by MuhammedKpln** [comment]
Will fix it once i find a proper icon!
