### ISSUE TITLE
Icon proposal

### ISSUE THREAD

**Issue by Zabriskije** [MuhammedKpln/spamify#6]
Hi @MuhammedKpln,
As mentioned in https://github.com/MuhammedKpln/spamify/issues/4, the current app and menu bar icons are not in line with Apple HIG.
I have an icon proposal for both. In case you like it, feel free to use it:
<img width="128" src="https://user-images.githubusercontent.com/101254295/162570436-5684482a-95c0-41fa-a91b-cf76183eaf75.png">
And here's the menu bar icon:  &nbsp;<img width="16" src="https://user-images.githubusercontent.com/101254295/162571141-21df0884-d715-418b-98f3-912bb71fbd50.png">

In [this ZIP file](https://github.com/MuhammedKpln/spamify/files/8456830/Spamify.zip), you'll find PNG + ICNS for the app icon, and PNG for the menu bar icon.

**Comment by MuhammedKpln** [comment]
Thanks for your work! Will release a new version with updated icons!
